# Generated by Django 4.2.7 on 2023-11-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='simplify',
            field=models.BooleanField(default=False),
        ),
    ]
